version: '2'
services:

    postgres:
        build:
            context: postgres/.
            dockerfile: Dockerfile
        env_file: .env
        ports:
            - "5432:5432"
        volumes:
            - ./data:/var/lib/postgresql/data

    app:
        build:
            context: .
            dockerfile: Dockerfile
        stdin_open: true
        tty: true
        env_file: .env
        volumes:
            - ./app:/app
        depends_on:
            - postgres
        links:
            - postgres:postgres
